spring:
  application:
    name: Springboot Drools Excel

server:
  port: 8081

debug: false

api:
  inquiry:
    v1: /inquiry/{type}
  check-eligibility-pos:
    v1: /eligibility/pos

drools:
  rules:
    eligibility:
      pos:
        - drools/rules/EligibilityPosDto.xls
        - drools/rules/response/pos/reject/DownPaymentReasonRejectPos.xls
        - drools/rules/response/pos/reject/AgeReasonRejectPos.xls